export enum StoreEnum {  
  Zentrale = 'Zentrale',  
  Bamberg = 'Bamberg',  
  BAInnenstadt = 'BA-Innenstadt',  
  BAHainpark = 'BA-Hainpark',  
  Erlangen = 'Erlangen',
  ERBruck = 'ER-Bruck',  
  Heroldsberg = 'Heroldsberg',  
  NMarienberg = 'N-Marienberg',  
  NNordostpark = 'N-Nordostpark',  
  NLangwasser = 'N-Langwasser',  
  NMaxfeld = 'N-Maxfeld',  
  NGalgenhof = 'N-Galgenhof',  
  NGleisshammer = 'N-Gleißhammer',  
  NPlaerrer = 'N-Plärrer',  
  NFinkenbrunn = 'N-Finkenbrunn',  
  FürthStadtpark = 'Fürth-Stadtpark',  
  FürthRathaus = 'Fürth-Rathaus',
  Cadolzburg = 'Cadolzburg',  
  Roth = 'Roth',  
  Wendelstein = 'Wendelstein',  
  WUGartenstadt = 'WU-Gartenstadt',  
  WUGrombuehl = 'WU-Grombühl'  
}
